name: (Standalone | Dev) Build and deploy standalone development build on Itch.io and Telegram

on:
  workflow_dispatch:

jobs:
  run:
    uses: mnicolas94/UnityCICDWorkflows/.github/workflows/BnD_standalone.yml@v1-pre-13
    with:
      development_build: true
      cache_tgsession: false
    secrets:
      TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      ITCH_BUTLER_CREDENTIALS: ${{ secrets.ITCH_BUTLER_CREDENTIALS }}
      ITCH_GAME: ${{ secrets.ITCH_GAME }}
      ITCH_USER: ${{ secrets.ITCH_USER }}